org.gradle.jvmargs=-Xmx768m -XX:MaxMetaspaceSize=256m -Dfile.encoding=UTF-8
android.useAndroidX=true
org.gradle.daemon=false
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=daemon


org.gradle.workers.max=1
kotlin.daemon.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m

