const router = require('express').Router();
const auth = require('../middleware/auth');
const upload = require('../middleware/upload');
const controller = require('../controllers/memberController');
const allowRoles = require('../middleware/role');

router.use(auth);
router.get('/', controller.list);
router.get('/birthdays', controller.birthdays);
router.get('/duplicates', controller.duplicates);
router.get('/suggestions', controller.suggestions);
router.get('/filter-options', controller.filterOptions);
router.get('/location-groups', controller.locationGroups);
router.get('/location-reviews', allowRoles('admin'), controller.locationReviews);
router.post('/location-reviews/:id/resolve', allowRoles('admin'), controller.resolveLocationReview);
router.get('/hierarchical-tree', controller.hierarchicalTree);
router.get('/party-analytics', controller.partyAnalytics);
router.post('/enrich-batch', allowRoles('admin'), controller.enrichBatch);
router.post('/bulk-party', controller.bulkParty);
router.post('/bulk-anubhag', controller.bulkAnubhag);
router.post('/bulk-vote-status', controller.bulkVoteStatus);
router.post('/assign-part-to-village', allowRoles('admin'), controller.assignPartToVillage);
router.post('/bulk-location-correction', allowRoles('admin'), controller.bulkLocationCorrection);
router.post('/recheck-ocr', allowRoles('admin'), controller.recheckOcr);
router.post('/:id/recheck-ocr', allowRoles('admin'), controller.recheckOcr);
router.delete('/bulk', controller.bulkDelete);
router.post('/bulk-delete', controller.bulkDelete);
router.delete('/', allowRoles('admin'), controller.removeAll);
router.post('/merge', controller.merge);
router.get('/labels', controller.labels);
router.post('/bulk-labels', controller.bulkLabels);
router.get('/groups', allowRoles('admin'), controller.listGroups);
router.post('/groups', allowRoles('admin'), controller.createGroup);
router.put('/groups/:id', allowRoles('admin'), controller.updateGroup);
router.delete('/groups/:id', allowRoles('admin'), controller.deleteGroup);
router.post('/groups/bulk-assign', allowRoles('admin'), controller.bulkAssignGroup);
router.put('/:id/groups', allowRoles('admin'), controller.assignMemberGroups);
router.post('/:id/favorite', controller.toggleFavorite);
router.get('/:id', controller.get);
router.post('/', upload.single('photo'), controller.create);
router.put('/:id', upload.single('photo'), controller.update);
router.delete('/:id', controller.remove);

module.exports = router;

