// Official Verified Booth Number (Part Number) -> Village & Gram Panchayat Mapping (Parts 1 to 103+)
// Source: 179 - Vidhansabha Official Master & Verified Electoral Roll

const boothToVillageMap = {
  1: { village: "भींटा", gramPanchayat: "भींटा" },
  2: { village: "भींटा", gramPanchayat: "भींटा" },
  3: { village: "धोरिया खेड़ा", gramPanchayat: "भींटा" },
  4: { village: "भटेवर", gramPanchayat: "भींटा" },
  5: { village: "सरेवड़ी", gramPanchayat: "सरेवड़ी" },
  6: { village: "सरेवड़ी", gramPanchayat: "सरेवड़ी" },
  7: { village: "लड़की", gramPanchayat: "सरेवड़ी" },
  8: { village: "रामा", gramPanchayat: "सरेवड़ी" },
  9: { village: "जलामाली", gramPanchayat: "सरेवड़ी" },
  10: { village: "छातोल", gramPanchayat: "छातोल" },
  11: { village: "मियाला", gramPanchayat: "छातोल" },
  12: { village: "बागड़", gramPanchayat: "बागड़" },
  13: { village: "सिरोड़ी", gramPanchayat: "बागड़" },
  14: { village: "कोट", gramPanchayat: "कोट" },
  15: { village: "कोट", gramPanchayat: "कोट" },
  16: { village: "टूणगाच", gramPanchayat: "कोट" },
  17: { village: "टूणगाच", gramPanchayat: "कोट" },
  18: { village: "खाखरमाला", gramPanchayat: "खाखरमाला" },
  19: { village: "आसूणा", gramPanchayat: "खाखरमाला" },
  20: { village: "मोखुन्दा", gramPanchayat: "मोखुन्दा" },
  21: { village: "मोखुन्दा", gramPanchayat: "मोखुन्दा" },
  22: { village: "मासिंगपुरा", gramPanchayat: "मासिंगपुरा" },
  23: { village: "मांडका खेड़ा", gramPanchayat: "मासिंगपुरा" },
  24: { village: "डूंगरी", gramPanchayat: "मासिंगपुरा" },
  25: { village: "झाड़ोल", gramPanchayat: "झाड़ोल" },
  26: { village: "झाड़ोल", gramPanchayat: "झाड़ोल" },
  27: { village: "झाड़ोल", gramPanchayat: "झाड़ोल" },
  28: { village: "टोकरा", gramPanchayat: "झाड़ोल" },
  29: { village: "सिंहपुरा", gramPanchayat: "झाड़ोल" },
  30: { village: "देवरिया", gramPanchayat: "देवरिया" },
  31: { village: "देवरिया", gramPanchayat: "देवरिया" },
  32: { village: "देवरिया", gramPanchayat: "देवरिया" },
  33: { village: "गलवा", gramPanchayat: "गलवा" },
  34: { village: "गलवा", gramPanchayat: "गलवा" },
  35: { village: "चारोट", gramPanchayat: "चारोट" },
  36: { village: "चारोट", gramPanchayat: "चारोट" },
  37: { village: "खेमाणा", gramPanchayat: "खेमाणा" },
  38: { village: "खेमाणा", gramPanchayat: "खेमाणा" },
  39: { village: "पालरां", gramPanchayat: "पालरां" },
  40: { village: "पालरां", gramPanchayat: "पालरां" },
  41: { village: "मेरिया खेड़ा", gramPanchayat: "पालरां" },
  42: { village: "पीथा का खेड़ा", gramPanchayat: "पीथा का खेड़ा" },
  43: { village: "मांडोल", gramPanchayat: "पीथा का खेड़ा" },
  44: { village: "बोराणा", gramPanchayat: "बोराणा" },
  45: { village: "बोराणा", gramPanchayat: "बोराणा" },
  46: { village: "बोराणा", gramPanchayat: "बोराणा" },
  47: { village: "बोराणा", gramPanchayat: "बोराणा" },
  48: { village: "धूल खेड़ा", gramPanchayat: "कलालखेड़ी" },
  49: { village: "धूल खेड़ा", gramPanchayat: "कलालखेड़ी" },
  50: { village: "कलालखेड़ी", gramPanchayat: "कलालखेड़ी" },
  51: { village: "कलालखेड़ी", gramPanchayat: "कलालखेड़ी" },
  52: { village: "बरी", gramPanchayat: "कलालखेड़ी" },
  53: { village: "सुरास", gramPanchayat: "सुरास" },
  54: { village: "सुरास", gramPanchayat: "सुरास" },
  55: { village: "पाबियों का खेड़ा", gramPanchayat: "सुरास" },
  56: { village: "बागोलिया", gramPanchayat: "बागोलिया" },
  57: { village: "बागोलिया", gramPanchayat: "बागोलिया" },
  58: { village: "थाला", gramPanchayat: "थाला" },
  59: { village: "गाडरी खेड़ा", gramPanchayat: "थाला" },
  60: { village: "चीतरपुरा", gramPanchayat: "थाला" },
  61: { village: "चीतरपुरा", gramPanchayat: "थाला" },
  62: { village: "सगरेव", gramPanchayat: "सगरेव" },
  63: { village: "सगरेव", gramPanchayat: "सगरेव" },
  64: { village: "रायपुर", gramPanchayat: "रायपुर" },
  65: { village: "रायपुर", gramPanchayat: "रायपुर" },
  66: { village: "रायपुर", gramPanchayat: "रायपुर" },
  67: { village: "रायपुर", gramPanchayat: "रायपुर" },
  68: { village: "रायपुर", gramPanchayat: "रायपुर" },
  69: { village: "रायपुर", gramPanchayat: "रायपुर" },
  70: { village: "केमरिया", gramPanchayat: "गल्यावड़ी" },
  71: { village: "केमरिया", gramPanchayat: "गल्यावड़ी" },
  72: { village: "गल्यावड़ी", gramPanchayat: "गल्यावड़ी" },
  73: { village: "गल्यावड़ी", gramPanchayat: "गल्यावड़ी" },
  74: { village: "नान्दशा जागीर", gramPanchayat: "नान्दशा जागीर" },
  75: { village: "पानोतिया", gramPanchayat: "पानोतिया" },
  76: { village: "पानोतिया", gramPanchayat: "पानोतिया" },
  77: { village: "खूटिया", gramPanchayat: "पानोतिया" },
  78: { village: "खूटिया", gramPanchayat: "पानोतिया" },
  79: { village: "मोखमपुरा", gramPanchayat: "नाथड़ियास" },
  80: { village: "नाथड़ियास", gramPanchayat: "नाथड़ियास" },
  81: { village: "आसपुर", gramPanchayat: "नाथड़ियास" },
  82: { village: "पानोतिया", gramPanchayat: "पानोतिया" },
  83: { village: "जोगरास", gramPanchayat: "नाहरी" },
  84: { village: "जोगरास", gramPanchayat: "नाहरी" },
  85: { village: "नाहरी", gramPanchayat: "नाहरी" },
  86: { village: "फतेहपुरा", gramPanchayat: "नाहरी" },
  87: { village: "फतेहपुरा", gramPanchayat: "नाहरी" },
  88: { village: "नारायणखेड़ा", gramPanchayat: "नारायणखेड़ा" },
  89: { village: "बाड़िया कलां", gramPanchayat: "नारायणखेड़ा" },
  90: { village: "बाड़िया खुर्द", gramPanchayat: "बकाण" },
  91: { village: "लखाहाली", gramPanchayat: "आशाहोली" },
  92: { village: "रामरास", gramPanchayat: "आशाहोली" },
  93: { village: "आशाहोली", gramPanchayat: "आशाहोली" },
  94: { village: "आशाहोली", gramPanchayat: "आशाहोली" },
  95: { village: "लेली तोलास", gramPanchayat: "आशाहोली" },
  96: { village: "देवाड़ा", gramPanchayat: "बोरियापुरा" },
  97: { village: "नरियापुरा", gramPanchayat: "बोरियापुरा" },
  98: { village: "नरियापुरा", gramPanchayat: "बोरियापुरा" },
  99: { village: "उड़सीपुरा", gramPanchayat: "बोरियापुरा" },
  100: { village: "उड़सीपुरा", gramPanchayat: "बोरियापुरा" },
  101: { village: "आमली", gramPanchayat: "आमली" },
  102: { village: "आमली", gramPanchayat: "आमली" },
  103: { village: "आमली", gramPanchayat: "आमली" }
};

function getMasterLocationForBooth(partNumber) {
  const p = parseInt(String(partNumber || '').trim(), 10);
  if (!isNaN(p) && boothToVillageMap[p]) {
    return boothToVillageMap[p];
  }
  return null;
}

module.exports = {
  boothToVillageMap,
  getMasterLocationForBooth
};
